iso3_to_iso2 = {
    'afr': 'af', 'gax_ars': 'None', 'ind': 'id', 'msa': 'ms', 'jav': 'jv', 'bis': 'bi', 'bre': 'br', 'cat': 'ca',
    'ces': 'cs', 'nya': 'ny', 'sna': 'sn', 'cos': 'co', 'cym': 'cy', 'dan': 'da', 'deu': 'de', 'div': 'dv', 'eng': 'en',
    'spa': 'es', 'spa_es': 'es', 'epo': 'eo', 'eus': 'eu', 'ewe': 'ee', 'tgl': 'tl', 'fra': 'fr', 'fao': 'fo',
    'gle': 'ga', 'glv': 'gv', 'smo': 'sm', 'gla': 'gd', 'glg': 'gl', 'kik': 'ki', 'hau': 'ha', 'hwc': 'hw', 'hmo': 'ho',
    'hrv': 'hr', 'ibo': 'ig', 'nde': 'nd', 'nbl': 'nr', 'xho': 'xh', 'zul': 'zu', 'isl': 'is', 'ita': 'it', 'cor': 'kw',
    'kin': 'rw', 'swh': 'sw', 'hat': 'ht', 'kmr': 'ku', 'lat': 'la', 'lvs': 'lv', 'ton': 'to', 'lit': 'lt', 'lin': 'ln',
    'lug': 'lg', 'hun': 'hu', 'plt': 'mg', 'mlt': 'mt', 'mri': 'mi', 'nav': 'nv', 'nld': 'nl', 'nob': 'nb', 'nno': 'nn',
    'kua': 'kj', 'ndo': 'ng', 'pol': 'pl', 'por': 'pt', 'por_pt': 'pt', 'ron': 'ro', 'san': 'sa', 'sag': 'sg',
    'sot': 'st', 'tsn': 'tn', 'sqi': 'sq', 'ssw': 'ss', 'slk': 'sk', 'slv': 'sl', 'som': 'so', 'sun': 'su', 'fin': 'fi',
    'swe': 'sv', 'vie': 'vi', 'ven': 've', 'tur': 'tr', 'twi': 'tw', 'vol': 'vo', 'fij': 'fj', 'tso': 'ts', 'yor': 'yo',
    'zom': 'zo', 'ell': 'el', 'bak': 'ba', 'bel': 'be', 'bul': 'bg', 'oss': 'os', 'kir': 'ky', 'ava': 'av', 'mkd': 'mk',
    'khk': 'mn', 'che': 'ce', 'rus': 'ru', 'srp': 'sr', 'tat': 'tt', 'tgk': 'tg', 'tuk': 'tk', 'uig_cyr': 'ug',
    'ukr': 'uk', 'chv': 'cv', 'hye': 'hy', 'heb': 'he', 'urd': 'ur', 'arb': 'ar', 'tuk_arb': 'tk', 'snd': 'sd',
    'pes': 'fa', 'uig': 'ug', 'ckb': 'ku_IQ', 'npi': 'ne', 'mar': 'mr', 'hin': 'hi', 'asm': 'as', 'ben': 'bn',
    'pan': 'pa', 'guj': 'gu', 'tam': 'ta', 'tel': 'te', 'kan': 'kn', 'mal': 'ml', 'sin': 'si', 'tha': 'th', 'lao': 'lo',
    'bod': 'bo', 'mya': 'my', 'mya_zaw': 'my', 'kat': 'ka', 'kor': 'ko', 'amh': 'am', 'khm': 'km', 'jpn': 'ja',
    'zho_tw': 'zh', 'zho': 'zh', 'orm': 'om', 'oci': 'oc', 'roh': 'rm', 'que': 'qu', 'ori': 'or', 'pli': 'pi',
    'fas': 'fa', 'nep': 'ne', 'mao': 'mi', 'mlg': 'mg', 'nau': 'na', 'tir': 'ti', 'zha': 'za', 'wol': 'wo', 'hbs': 'sh',
    'iii': 'ii', 'sme': 'se', 'run': 'rn', 'tah': 'ty', 'slo': 'sk', 'aym': 'ay', 'cha': 'ch', 'bos': 'bs', 'chu': 'cu',
    'dut': 'nl', 'dzo': 'dz', 'arm': 'hy', 'arg': 'an', 'aar': 'aa', 'abk': 'ab', 'alb': 'sq', 'ipk': 'ik', 'aka': 'ak',
    'baq': 'eu', 'bih': 'bh', 'bam': 'bm', 'kaz': 'kk', 'kom': 'kv', 'kas': 'ks', 'lim': 'li', 'kur': 'ku', 'kal': 'kl',
    'est': 'et', 'ful': 'ff', 'fry': 'fy', 'wln': 'wa', 'fre': 'fr', 'ile': 'ie', 'ina': 'ia', 'ido': 'io', 'iku': 'iu',
    'her': 'hz'
}
